version: 2
updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 20
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "04:00"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
